### ISSUE TITLE
`3.29.0` release seems to be broken on Python 3.9 and earlier due to `importlib_metadata` backport

### ISSUE THREAD

**Issue by agriyakhetarpal** [scikit-build/cmake-python-distributions#472] opened 2024-03-26 14:10 UTC
CMake seems to use the `importlib_metadata` backport dependency for Python 3.8 and 3.9, but maybe it's not declaring that?

I noticed the failure in the CI logs, and then triggered a re-run just in case this was a one-off failure:
1. https://github.com/pybamm-team/PyBaMM/actions/runs/8436810245/job/23105126965
2. https://github.com/pybamm-team/PyBaMM/actions/runs/8436810245/job/23106957328

Edit: okay so it is declaring that, just in the optional dependencies table: https://github.com/scikit-build/cmake-python-distributions/blob/85a457bf3e0de6efa65cc0f47f017810936772f0/pyproject.toml#L36-L42

and I suppose it should be a required dependency too. It's being used here: https://github.com/scikit-build/cmake-python-distributions/blob/85a457bf3e0de6efa65cc0f47f017810936772f0/src/cmake/__init__.py#L5-L9

**Comment by mloubout** [comment] 2024-03-26 14:50
The issue is that `importlib` change is for python >= 3.8 not > 3.10 so it should be 

```
if sys.version_info < (3, 8): 
     from importlib_metadata import distribution 
 else: 
     from importlib.metadata import distribution 
```

**Comment by mloubout** [comment] 2024-03-26 14:53
I filed a patch for it in case people agree it is correct. Can a release be made if the patch gets merged?

**Comment by braindevices** [comment] 2024-03-26 15:05
this affect us too

**Comment by henryiii** [comment] 2024-03-26 16:09
3.29.0 is yanked and we'll produce a 3.29.0.1 later today.

**Closed** 2024-03-26 16:27 UTC

**Comment by henryiii** [comment] 2024-03-26 20:55
New version out!

**Comment by mloubout** [comment] 2024-03-26 21:09
Fixed the issue on my side thanks!
