### ISSUE TITLE
  Installing build dependencies ... error   error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by DhruvSinghBora** [scikit-build/cmake-python-distributions#384] opened 2023-07-24 13:42 UTC
ERROR: Command errored out with exit status 1:
   command: /home/iot/projectA/env/bin/python3 /home/iot/projectA/env/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3eqs8m5g/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- 'cmake>=3.1' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.0; python_version=='"'"'3.7'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.5; python_version=='"'"'3.8'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'linux'"'"' and platform_machine == '"'"'aarch64'"'"'' 'numpy==1.21.0; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'darwin'"'"' and platform_machine == '"'"'arm64'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.21.2; python_version=='"'"'3.10'"'"' and platform_system!='"'"'Darwin'"'"'' 'numpy==1.21.4; python_version=='"'"'3.10'"'"' and platform_system=='"'"'Darwin'"'"'' 'numpy==1.22.2; python_version>='"'"'3.11'"'"'' pip 'scikit-build>=0.14.0' setuptools==59.2.0
       cwd: None
  Complete output (77 lines):
  Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
  Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.10" and platform_system != "Darwin"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Darwin"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.11"' don't match your environment
  Collecting cmake>=3.1
    Using cached cmake-3.27.0.tar.gz (35 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting numpy==1.19.3
    Using cached https://www.piwheels.org/simple/numpy/numpy-1.19.3-cp39-cp39-linux_armv7l.whl (10.5 MB)
  Collecting pip
    Using cached https://www.piwheels.org/simple/pip/pip-23.2.1-py3-none-any.whl (2.1 MB)
  Collecting scikit-build>=0.14.0
    Using cached https://www.piwheels.org/simple/scikit-build/scikit_build-0.17.6-py3-none-any.whl (84 kB)
  Collecting setuptools==59.2.0
    Using cached https://www.piwheels.org/simple/setuptools/setuptools-59.2.0-py3-none-any.whl (952 kB)
  Collecting tomli
    Using cached https://www.piwheels.org/simple/tomli/tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting wheel>=0.32.0
    Using cached https://www.piwheels.org/simple/wheel/wheel-0.41.0-py3-none-any.whl (64 kB)
  Collecting distro
    Using cached https://www.piwheels.org/simple/distro/distro-1.8.0-py3-none-any.whl (20 kB)
  Collecting packaging
    Using cached https://www.piwheels.org/simple/packaging/packaging-23.1-py3-none-any.whl (48 kB)
  Building wheels for collected packages: cmake
    Building wheel for cmake (PEP 517): started
    Building wheel for cmake (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/iot/projectA/env/bin/python3 /tmp/tmpb0x62lqe_in_process.py build_wheel /tmp/tmplrir_okb
         cwd: /tmp/pip-install-4ul50uzi/cmake_33d003c1126544b9825700bf2717ed47
    Complete output (33 lines):
    Traceback (most recent call last):
      File "/tmp/pip-build-env-yltzncuh/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
        cmkr = cmaker.CMaker(cmake_executable)
      File "/tmp/pip-build-env-yltzncuh/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 148, in __init__
        self.cmake_version = get_cmake_version(self.cmake_executable)
      File "/tmp/pip-build-env-yltzncuh/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
        raise SKBuildError(msg) from err

        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cmake:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
           order to retrieve the last manylinux1 compatible wheel.
        3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
           requirements in order to retrieve the last manylinux1 compatible wheel.
        4) Open an issue with the debug information that follows at
           https://github.com/scikit-build/cmake-python-distributions/issues

        Python: 3.9.2
        platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
        glibc: glibc 2.31
        machine: aarch64
        bits: 32
        pip: n/a
        setuptools: 68.0.0
        scikit-build: 0.17.6
        PEP517_BUILD_BACKEND=setuptools.build_meta
        =============================DEBUG ASSISTANCE=============================

    Problem with the CMake installation, aborting build. CMake executable is cmake
    ----------------------------------------
    ERROR: Failed building wheel for cmake
  Failed to build cmake
  ERROR: Could not build wheels for cmake which use PEP 517 and cannot be installed directly
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/fa/1d/990ad4eb4d385fabb2773170cf865977b6d5b558dd51459672f7cf7d1847/opencv-python-4.8.0.74.tar.gz#sha256=009e3ce356a0cd2d7423723e00a32fd3d3cc5bb5970ed27a9a1f8a8f221d1db5 (from https://pypi.org/simple/opencv-python/) (requires-python:>=3.6). Command errored out with exit status 1: /home/iot/projectA/env/bin/python3 /home/iot/projectA/env/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-3eqs8m5g/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- 'cmake>=3.1' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.0; python_version=='"'"'3.7'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.5; python_version=='"'"'3.8'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'linux'"'"' and platform_machine == '"'"'aarch64'"'"'' 'numpy==1.21.0; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'darwin'"'"' and platform_machine == '"'"'arm64'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.21.2; python_version=='"'"'3.10'"'"' and platform_system!='"'"'Darwin'"'"'' 'numpy==1.21.4; python_version=='"'"'3.10'"'"' and platform_system=='"'"'Darwin'"'"'' 'numpy==1.22.2; python_version>='"'"'3.11'"'"'' pip 'scikit-build>=0.14.0' setuptools==59.2.0 Check the logs for full command output.
  Downloading opencv-python-4.7.0.72.tar.gz (91.1 MB)
     |████████████████████████████████| 91.1 MB 15 kB/s
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/iot/projectA/env/bin/python3 /home/iot/projectA/env/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-r0tvzefx/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools==59.2.0 wheel==0.37.0 'cmake>=3.1' pip 'scikit-build>=0.13.2' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.0; python_version=='"'"'3.7'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.19.3; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'linux'"'"' and platform_machine == '"'"'aarch64'"'"'' 'numpy==1.21.0; python_version<='"'"'3.9'"'"' and sys_platform == '"'"'darwin'"'"' and platform_machine == '"'"'arm64'"'"'' 'numpy==1.19.3; python_version=='"'"'3.9'"'"' and platform_machine != '"'"'aarch64'"'"' and platform_machine != '"'"'arm64'"'"'' 'numpy==1.21.2; python_version=='"'"'3.10'"'"' and platform_system!='"'"'Darwin'"'"'' 'numpy==1.21.4; python_version=='"'"'3.10'"'"' and platform_system=='"'"'Darwin'"'"'' 'numpy==1.22.0; python_version>='"'"'3.11'"'"''
       cwd: None
  Complete output (77 lines):
  Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
  Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version <= "3.9" and sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and platform_machine != "aarch64" and platform_machine != "arm64"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.10" and platform_system != "Darwin"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Darwin"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.11"' don't match your environment
  Collecting setuptools==59.2.0
    Using cached https://www.piwheels.org/simple/setuptools/setuptools-59.2.0-py3-none-any.whl (952 kB)
  Collecting wheel==0.37.0
    Downloading https://www.piwheels.org/simple/wheel/wheel-0.37.0-py2.py3-none-any.whl (35 kB)
  Collecting cmake>=3.1
    Using cached cmake-3.27.0.tar.gz (35 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting pip
    Using cached https://www.piwheels.org/simple/pip/pip-23.2.1-py3-none-any.whl (2.1 MB)
  Collecting scikit-build>=0.13.2
    Using cached https://www.piwheels.org/simple/scikit-build/scikit_build-0.17.6-py3-none-any.whl (84 kB)
  Collecting numpy==1.19.3
    Using cached https://www.piwheels.org/simple/numpy/numpy-1.19.3-cp39-cp39-linux_armv7l.whl (10.5 MB)
  Collecting tomli
    Using cached https://www.piwheels.org/simple/tomli/tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting packaging
    Using cached https://www.piwheels.org/simple/packaging/packaging-23.1-py3-none-any.whl (48 kB)
  Collecting distro
    Using cached https://www.piwheels.org/simple/distro/distro-1.8.0-py3-none-any.whl (20 kB)
  Building wheels for collected packages: cmake
    Building wheel for cmake (PEP 517): started
    Building wheel for cmake (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/iot/projectA/env/bin/python3 /tmp/tmpaqdf46ii_in_process.py build_wheel /tmp/tmpcsxeixeu
         cwd: /tmp/pip-install-zkry3grg/cmake_75fa7f606c3f41fabde81de6e36d0c88
    Complete output (33 lines):
    Traceback (most recent call last):
      File "/tmp/pip-build-env-tcf4x4ak/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
        cmkr = cmaker.CMaker(cmake_executable)
      File "/tmp/pip-build-env-tcf4x4ak/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 148, in __init__
        self.cmake_version = get_cmake_version(self.cmake_executable)
      File "/tmp/pip-build-env-tcf4x4ak/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
        raise SKBuildError(msg) from err

        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cmake:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
           order to retrieve the last manylinux1 compatible wheel.
        3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
           requirements in order to retrieve the last manylinux1 compatible wheel.
        4) Open an issue with the debug information that follows at
           https://github.com/scikit-build/cmake-python-distributions/issues

        Python: 3.9.2
        platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
        glibc: glibc 2.31
        machine: aarch64
        bits: 32
        pip: n/a
        setuptools: 68.0.0
        scikit-build: 0.17.6
        PEP517_BUILD_BACKEND=setuptools.build_meta
        =============================DEBUG ASSISTANCE=============================

    Problem with the CMake installation, aborting build. CMake executable is cmake
    ----------------------------------------
    ERROR: Failed building wheel for cmake
  Failed to build cmake
  ERROR: Could not build wheels for cmake which use PEP 517 and cannot be installed directly
  ----------------------------------------

**Comment by mayeut** [comment] 2023-08-12 09:58
duplicate of https://github.com/scikit-build/cmake-python-distributions/issues/392

**Closed by mayeut** 2023-08-12 09:58 UTC
