### ISSUE TITLE
Difficulty installing OpenCV

### ISSUE THREAD

**Issue by enseignement-Aouadi** [scikit-build/cmake-python-distributions#386] opened 2023-07-29 16:36 UTC
Hello, 
I try to install OpenCV on raspbian pi .
The machine remains on this task for 50 minutes, and it seems to be executing various tasks. Eventually, it ends up giving an error message.
Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [2536 lines of output]

It ends the error message with:
   =============================DEBUG ASSISTANCE=============================
                If you are seeing a compilation error please try the following steps to
                successfully install cmake:
                1) Upgrade to the latest pip and try again. This will fix errors for most
                   users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
                2) If on Linux, with glibc < 2.12, you can set PIP_ONLY_BINARY=cmake in
                   order to retrieve the last manylinux1 compatible wheel.
                3) If on Linux, with glibc < 2.12, you can cap "cmake<3.23" in your
                   requirements in order to retrieve the last manylinux1 compatible wheel.
                4) Open an issue with the debug information that follows at
                   https://github.com/scikit-build/cmake-python-distributions/issues

                Python: 3.9.2
                platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
                glibc: glibc 2.31
                machine: aarch64
                bits: 32
                pip: n/a
                setuptools: 68.0.0
                scikit-build: 0.17.6
                PEP517_BUILD_BACKEND=setuptools.build_meta

However, I have the latest version of CMake already installed on the machine.
I don't know what else to do, can you explain to me what is wrong?

**Comment by mayeut** [comment] 2023-08-12 09:56
duplicate of #392

**Closed by mayeut** 2023-08-12 09:56 UTC
